apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teacher-chart.fullname" . }}
  labels:
    {{- include "teacher-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "teacher-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "teacher-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "teacher-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - mountPath: "/data"
              name: teacher-storage 
          livenessProbe:
            httpGet:
              path: {{.Values.livenessProbe.httpGet.path}}
              port: {{.Values.livenessProbe.httpGet.port}}
          readinessProbe:
            httpGet:
              path: {{.Values.readinessProbe.httpGet.path}}
              port: {{.Values.readinessProbe.httpGet.port}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: teacher-storage
          persistentVolumeClaim:
            claimName: teacher-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
